# user on ubuntu-laptop (localhost)
#db.username=root
#db.password=dP~8%+w!~V4/7Tvw

# user on ubuntu-GCP & laptop (remote)
db.username=leon
db.password=vaqneb-Rucgar-turfe6

db.url=jdbc:mysql://my-mysql:3306/mySRD?serverTimezone=America/Chicago
db.driver=com.mysql.cj.jdbc.Driver
redis.ip=my-redis
redis.port=6379
redis.password=dP~8%+w!~V4/7Tvw
redis.user=redis

file.path=/usr/local/tomcat/files/

#db.url=jdbc:mysql://cloud.leon-sun.com:3306/mySRD?serverTimezone=America/Chicago
#db.driver=com.mysql.cj.jdbc.Driver
#redis.ip=cloud.leon-sun.com
#redis.port=6379
#redis.password=dP~8%+w!~V4/7Tvw
#redis.user=redis
#
#file.path=/Users/Leons/Downloads/temp
